# Generated by Django 5.1.4 on 2025-01-11 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_tweeter_remove_tweet_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tweeter',
        ),
    ]
